name: zero2prod
region: ams3
services: 
  - name: zero2prod
    dockerfile_path: Dockerfile
    source_dir: .
    image:
      registry_type: DOCR
      registry: antonzub1
      repository: zero2prod
      tag: latest
    health_check: 
      http_path: /health_check
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: APP_DATABASE__USERNAME
        scope: RUN_TIME
        value: ${newsletter.USERNAME}
      - key: APP_DATABASE__PASSWORD
        scope: RUN_TIME
        value: ${newsletter.PASSWORD}
      - key: APP_DATABASE__HOST
        scope: RUN_TIME
        value: ${newsletter.HOSTNAME}
      - key: APP_DATABASE__PORT
        scope: RUN_TIME
        value: ${newsletter.PORT}
      - key: APP_DATABASE__DATABASE_NAME
        scope: RUN_TIME
        value: ${newsletter.DATABASE}
databases:
  - engine: PG
    name: newsletter
    production: true
    num_nodes: 1
    version: "17"
    cluster_name: "app-d37c6188-4b85-47c4-a5ea-1578457cc12d"
